# Generated by Django 4.0.3 on 2022-04-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=400, unique=True)),
                ('insprice', models.FloatField(default=0)),
                ('taxrate', models.CharField(default='B', max_length=3)),
                ('synced', models.IntegerField(default=0)),
                ('itemclscode', models.CharField(max_length=30)),
                ('pckagunitcode', models.CharField(default='NT', max_length=20)),
                ('package', models.IntegerField(default=1)),
                ('qtyunitycode', models.CharField(default='U', max_length=20)),
                ('barcode', models.CharField(max_length=30)),
                ('itemtypcode', models.CharField(default='2', max_length=10)),
                ('nationcode', models.CharField(default='RW', max_length=20)),
                ('vsdcsent', models.CharField(default='N', max_length=20)),
                ('standardname', models.CharField(max_length=400)),
                ('batchno', models.CharField(max_length=20)),
                ('registbranchid', models.CharField(max_length=10)),
                ('dftprice', models.FloatField(default=0)),
                ('grp1price', models.FloatField(default=0)),
                ('grp2price', models.FloatField(default=0)),
                ('grp3price', models.FloatField(default=0)),
                ('grp4price', models.FloatField(default=0)),
                ('grp5price', models.FloatField(default=0)),
                ('addinfo', models.CharField(max_length=25)),
                ('saftyqty', models.FloatField(default=0)),
                ('insuranceapplicable', models.CharField(default='N', max_length=4)),
                ('usedorunused', models.CharField(default='N', max_length=4)),
                ('lastreqdate', models.CharField(max_length=30)),
            ],
        ),
    ]
